### ISSUE TITLE
Check if there are some missing dependencies

### ISSUE THREAD

**Issue by HosameldinMohamed** [ami-iit/robot-log-visualizer#26]
I used the visualizer in my PC, and it seems I am missing some dependencies.

- First, when I build the system using `pip install .`, I get the follwoing error,

<details>
<summary>Install </summary>

```
Building wheels for collected packages: robot-log-visualizer, idyntree
  Building wheel for robot-log-visualizer (PEP 517) ... done
  Created wheel for robot-log-visualizer: filename=robot_log_visualizer-0.1.0-py3-none-any.whl size=20263 sha256=8f03952aca0696372ae3db8bc294487781e6841d3863c3acc806223cfb857b96
  Stored in directory: /tmp/pip-ephem-wheel-cache-td1i6fnr/wheels/b4/63/34/edfad2463e62e67ed7e451004b243aa380262e1379b21076f6
  Building wheel for idyntree (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hosameldin/code/robot-log-visualizer/venv/bin/python /home/hosameldin/code/robot-log-visualizer/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpbcb7_gk5
       cwd: /tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d
  Complete output (86 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 11.2.0
  -- The CXX compiler identification is GNU 11.2.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at cmake/iDynTreeDependencies.cmake:62 (find_package):
    Could not find a package configuration file provided by "Eigen3" (requested
    version 3.2.92) with any of the following names:
  
      Eigen3Config.cmake
      eigen3-config.cmake
  
    Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
    "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
    provides a separate development package or SDK, be sure it has been
    installed.
  Call Stack (most recent call first):
    CMakeLists.txt:39 (include)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/temp.linux-x86_64-3.10_BuildAndInstall/CMakeFiles/CMakeOutput.log".
  
  ==> Configuring:
  $ cmake -S /tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d -B /tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/temp.linux-x86_64-3.10_BuildAndInstall -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/lib.linux-x86_64-3.10/idyntree -DBUILD_SHARED_LIBS:BOOL=OFF -DIDYNTREE_USES_PYTHON:BOOL=ON -DIDYNTREE_COMPILE_TESTS:BOOL=OFF -DIDYNTREE_PACKAGE_FOR_PYPI:BOOL=ON -DIDYNTREE_USES_IPOPT:BOOL=ON -DIDYNTREE_USES_ASSIMP:BOOL=ON -DIDYNTREE_USES_IRRLICHT:BOOL=OFF -DIDYNTREE_USES_QT5:BOOL=OFF -DIDYNTREE_USES_OSQPEIGEN:BOOL=OFF -DIDYNTREE_USES_ALGLIB:BOOL=OFF -DIDYNTREE_USES_WORHP:BOOL=OFF -DIDYNTREE_USES_YARP:BOOL=OFF -DIDYNTREE_USES_ICUB_MAIN:BOOL=OFF -DIDYNTREE_PYTHON_PIP_METADATA_INSTALL:BOOL=OFF
  
  ==> Building:
  $ cmake --build /tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/temp.linux-x86_64-3.10_BuildAndInstall --config Release
  
  ==> Installing:
  $ cmake --install /tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/temp.linux-x86_64-3.10_BuildAndInstall
  
  Traceback (most recent call last):
    File "/home/hosameldin/code/robot-log-visualizer/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/hosameldin/code/robot-log-visualizer/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/hosameldin/code/robot-log-visualizer/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 11, in <module>
      setuptools.setup(
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/cmake_build_extension/build_extension.py", line 110, in run
      self.build_extension(ext)
    File "/tmp/pip-build-env-ke2befbp/overlay/lib/python3.10/site-packages/cmake_build_extension/build_extension.py", line 224, in build_extension
      subprocess.check_call(configure_command)
    File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d', '-B', '/tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/temp.linux-x86_64-3.10_BuildAndInstall', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-mgaw78v8/idyntree_9e434d6e8e2245b8b3111589f1e0135d/build/lib.linux-x86_64-3.10/idyntree', '-DBUILD_SHARED_LIBS:BOOL=OFF', '-DIDYNTREE_USES_PYTHON:BOOL=ON', '-DIDYNTREE_COMPILE_TESTS:BOOL=OFF', '-DIDYNTREE_PACKAGE_FOR_PYPI:BOOL=ON', '-DIDYNTREE_USES_IPOPT:BOOL=ON', '-DIDYNTREE_USES_ASSIMP:BOOL=ON', '-DIDYNTREE_USES_IRRLICHT:BOOL=OFF', '-DIDYNTREE_USES_QT5:BOOL=OFF', '-DIDYNTREE_USES_OSQPEIGEN:BOOL=OFF', '-DIDYNTREE_USES_ALGLIB:BOOL=OFF', '-DIDYNTREE_USES_WORHP:BOOL=OFF', '-DIDYNTREE_USES_YARP:BOOL=OFF', '-DIDYNTREE_USES_ICUB_MAIN:BOOL=OFF', '-DIDYNTREE_PYTHON_PIP_METADATA_INSTALL:BOOL=OFF']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for idyntree
Successfully built robot-log-visualizer
Failed to build idyntree
ERROR: Could not build wheels for idyntree which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/home/hosameldin/code/robot-log-visualizer/venv/bin/python -m pip install --upgrade pip' command.
```

</details>

It seems that it's looking for `Eigen3` to build `iDynTree`, but I don't have installed.

I have a Conda environment where the dependencies of `robotology-superbuild` are installed. When I activate it the installation goes through without issues.

- During running I don't see the visualizer with the robot model.
![image](https://user-images.githubusercontent.com/45564317/157096608-24f843ff-e03d-43a4-80ac-4be8da6fb636.png)

However, I can launch the visualiser using a browser with the address shown in the terminal.

<details>
<summary>My pip list</summary>

```
Package           Version
----------------- -------
asttokens         2.0.5
backcall          0.2.0
black             22.1.0
click             8.0.3
control           0.9.1
cycler            0.11.0
debugpy           1.5.1
decorator         5.1.1
entrypoints       0.4
executing         0.8.2
fonttools         4.29.1
ipykernel         6.9.0
ipython           8.0.1
jedi              0.18.1
jupyter-client    7.1.2
jupyter-core      4.9.1
kiwisolver        1.3.2
matplotlib        3.5.1
matplotlib-inline 0.1.3
mypy-extensions   0.4.3
nest-asyncio      1.5.4
numpy             1.22.2
parso             0.8.3
pathspec          0.9.0
pexpect           4.8.0
pickleshare       0.7.5
pip               22.0.3
platformdirs      2.5.0
prompt-toolkit    3.0.28
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.11.2
python-dateutil   2.8.2
pyzmq             22.3.0
scipy             1.8.0
setuptools        60.9.3
stack-data        0.1.4
tornado           6.1
traitlets         5.1.1
wcwidth           0.2.5
wheel             0.37.1

```

</details>

<details>
<summary>My conda list</summary>

```
# packages in environment at /home/hosameldin/mambaforge/envs/robTest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h5bd9786_13    conda-forge
ace                       7.0.6                h9c3ff4c_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
ampl-mp                   3.1.0             h2cc385e_1006    conda-forge
aom                       3.2.0                h9c3ff4c_2    conda-forge
asio                      1.14.1               h9c3ff4c_1    conda-forge
assimp                    5.2.1                hedfc422_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
bash-completion           2.11                          0    conda-forge
binutils                  2.36.1               hdd6e379_2    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_5    conda-forge
bison                     3.8                  h9c3ff4c_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boost                     1.74.0          py310h7c3ba0c_5    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
bullet-cpp                3.21                 hb5077e9_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-compiler                1.4.0                h166bdaf_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
cmake                     3.22.2               h1021d11_0    conda-forge
compilers                 1.4.0                ha770c72_0    conda-forge
console_bridge            1.0.1                h4bd325d_0    conda-forge
cppzmq                    4.8.1                hf7cf922_0    conda-forge
curl                      7.81.0               h2574ce0_0    conda-forge
cxx-compiler              1.4.0                h924138e_0    conda-forge
dartsim                   6.12.1               h7529616_2    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
expat                     2.4.5                h27087fc_0    conda-forge
expat-cos7-x86_64         2.1.0             h9b0a68f_1105    conda-forge
fcl                       0.7.0                h2cbc392_0    conda-forge
ffmpeg                    4.4.1                h6987444_1    conda-forge
flann                     1.9.1             hfe772e8_1010    conda-forge
flex                      2.6.4             h58526e2_1004    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fortran-compiler          1.4.0                h2a4ca65_0    conda-forge
freeglut                  3.2.2                h9c3ff4c_1    conda-forge
freeimage                 3.18.0               h88c329d_7    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gazebo                    11.10.1              h68334f2_4    conda-forge
gcc                       10.3.0               he2824d0_5    conda-forge
gcc_impl_linux-64         10.3.0              hf2f2afa_12    conda-forge
gcc_linux-64              10.3.0               hc39de41_5    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
geos                      3.10.1               h9c3ff4c_1    conda-forge
geotiff                   1.7.0                h90a4e78_5    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gfortran                  10.3.0               h18518b4_5    conda-forge
gfortran_impl_linux-64    10.3.0              h73f4979_12    conda-forge
gfortran_linux-64         10.3.0               hb09a455_5    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
glfw                      3.3.6                h7f98852_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h85b4f2f_1    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
gtk2                      2.24.33              h539f30e_1    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
gxx                       10.3.0               he2824d0_5    conda-forge
gxx_impl_linux-64         10.3.0              hf2f2afa_12    conda-forge
gxx_linux-64              10.3.0               h2593f52_5    conda-forge
harfbuzz                  3.1.1                h83ec7ef_0    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_103    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
ilmbase                   2.5.5                h780b84a_0    conda-forge
ipopt                     3.14.4               h7ede334_0    conda-forge
irrlicht                  1.8.5                hdaeae82_0    conda-forge
jasper                    2.0.33               ha77e612_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
jsoncpp                   1.9.5                h4bd325d_1    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.14               h87e4c3c_3    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_13    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libccd                    2.1                  h9c3ff4c_1    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdc1394                 2.2.6                he1b5a44_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libdrm                    2.4.109              h7f98852_0    conda-forge
libdrm-cos7-x86_64        2.4.97            h9b0a68f_1105    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     10.3.0              he6cfe16_12    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgd                     2.3.3                h6ad9fb6_0    conda-forge
libgdal                   3.4.0               h4471fe2_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libglvnd-cos7-x86_64      1.0.1             h9b0a68f_1105    conda-forge
libglvnd-glx-cos7-x86_64  1.0.1             h9b0a68f_1105    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libi2c                    4.3                  h9c3ff4c_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libignition-cmake2        2.10.0               h9c3ff4c_0    conda-forge
libignition-common3       3.13.2               ha44c05f_1    conda-forge
libignition-fuel-tools4   4.4.0                hfaf2eda_6    conda-forge
libignition-math6         6.10.0               h9c3ff4c_0    conda-forge
libignition-msgs5         5.7.0                h42850c7_2    conda-forge
libignition-tools1        1.4.1                h33ecc0d_2    conda-forge
libignition-transport8    8.1.0                h12d6754_9    conda-forge
libjpeg-turbo             2.1.1                h7f98852_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
liblapacke                3.9.0           13_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libmatio                  1.5.21               hdf44fe6_1    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.46.0               h812cca2_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libode                    0.16.2               h122e73d_9    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopencv                 4.5.5            py31he7a5e20_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
libraw                    0.20.2               h10796ff_1    conda-forge
librsvg                   2.52.5               hc3c00ef_1    conda-forge
librttopo                 1.1.0                h30b5eef_8    conda-forge
libsanitizer              10.3.0              h26c7422_12    conda-forge
libsdformat               9.3.0                h21f569a_5    conda-forge
libselinux-cos7-x86_64    2.5               h9b0a68f_1105    conda-forge
libsepol-cos7-x86_64      2.5               h9b0a68f_1105    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialite             5.0.1               hf3ee066_12    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  10.3.0              he6cfe16_12    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtar                    1.2.20            h7f98852_1004    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  249                  h7f98852_1    conda-forge
libusb                    1.0.25             h4c0bc5a_100    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libva                     2.14.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libx11-common-cos7-x86_64 1.6.7             h9b0a68f_1105    conda-forge
libx11-cos7-x86_64        1.6.7             h9b0a68f_1105    conda-forge
libxau-cos7-x86_64        1.0.8             h9b0a68f_1105    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcb-cos7-x86_64        1.13              h9b0a68f_1105    conda-forge
libxdamage-cos7-x86_64    1.1.4             h9b0a68f_1105    conda-forge
libxext-cos7-x86_64       1.3.3             h9b0a68f_1105    conda-forge
libxfixes-cos7-x86_64     5.0.3             h9b0a68f_1105    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libxshmfence-cos7-x86_64  1.2               h9b0a68f_1105    conda-forge
libxshmfence-devel-cos7-x86_64 1.2               h9b0a68f_1105    conda-forge
libxxf86vm-cos7-x86_64    1.1.4             h9b0a68f_1105    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lua                       5.4.4                h25fbb91_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
m4                        1.4.18            h516909a_1001    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
mesa-khr-devel-cos7-x86_64 18.3.4            h9b0a68f_1105    conda-forge
mesa-libgl-cos7-x86_64    18.3.4            h9b0a68f_1105    conda-forge
mesa-libgl-devel-cos7-x86_64 18.3.4            h9b0a68f_1105    conda-forge
mesa-libglapi-cos7-x86_64 18.3.4            h9b0a68f_1105    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mumps-include             5.2.1               ha770c72_10    conda-forge
mumps-seq                 5.2.1               h47a8eb5_10    conda-forge
mysql-common              8.0.28               ha770c72_0    conda-forge
mysql-libs                8.0.28               hfa10184_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.10.2               h4bd325d_1    conda-forge
nlohmann_json             3.10.5               h9c3ff4c_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
numpy                     1.22.2          py310h454958d_0    conda-forge
octomap                   1.9.7                h4bd325d_0    conda-forge
ogre                      1.10.12              hf655ca9_7    conda-forge
openal-soft               1.21.1               h4bd325d_0    conda-forge
opencv                    4.5.5            py31hff52083_0    conda-forge
openexr                   2.5.5                hf817b99_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
poppler                   21.11.0              ha39eefc_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
portaudio                 19.6.0               hae3ed74_4    conda-forge
postgresql                13.5                 h2510834_1    conda-forge
proj                      8.2.0                h277dcde_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pugixml                   1.11.4               h9c3ff4c_0    conda-forge
py-opencv                 4.5.5            py31hfdc917e_0    conda-forge
python                    3.10.2          h85951f9_3_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qwt                       6.2.0                h7ec6b3e_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
rhash                     1.4.1                h7f98852_0    conda-forge
ruby                      3.1.1                h22ca3a2_0    conda-forge
scotch                    6.0.9                h3858553_1    conda-forge
sdl                       1.2.15               h9c3ff4c_1    conda-forge
sdl2                      2.0.18               h9c3ff4c_0    conda-forge
setuptools                60.9.3          py310hff52083_0    conda-forge
simbody                   3.7                  h64f3f5a_3    conda-forge
soxr                      0.1.2                         0    HCC
spdlog                    1.9.2                h4bd325d_1    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
svt-av1                   0.9.0                h27087fc_1    conda-forge
swig                      4.0.2                hd3c618e_2    conda-forge
sysroot_linux-64          2.17                h4a8ded7_13    conda-forge
tbb                       2021.5.0             h4bd325d_0    conda-forge
tbb-devel                 2021.5.0             h4bd325d_0    conda-forge
tiledb                    2.5.3                h2038895_0    conda-forge
tinyxml                   2.6.2                h4bd325d_2    conda-forge
tinyxml2                  9.0.0                h9c3ff4c_2    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzcode                    2021e                h7f98852_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unixodbc                  2.3.9                hb166930_0    conda-forge
urdfdom                   2.3.5                h4bd325d_0    conda-forge
urdfdom_headers           1.0.5                h4bd325d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
x265                      3.5                  h4bd325d_1    conda-forge
xerces-c                  3.2.3                h9d8b166_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxaw               1.0.14               h7f98852_1    conda-forge
xorg-libxcursor           1.2.0                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxinerama          1.1.4             h9c3ff4c_1001    conda-forge
xorg-libxmu               1.1.3                h7f98852_0    conda-forge
xorg-libxpm               3.5.13               h7f98852_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
zziplib                   0.13.69              h27826a3_1    conda-forge

```

</details>

**Comment by Nicogene** [comment]
I'd also add in the readme the thing that python >= 3.8 is required
