### ISSUE TITLE
robot-log-visualizer crashes if enviornment variables are not defined

### ISSUE THREAD

**Issue by paolo-viceconte** [ami-iit/robot-log-visualizer#55]
```
Traceback (most recent call last):
  File "/tmp/.mount_robot-CrNPEb/usr/src/robot_log_visualizer/ui/gui.py", line 651, in dropEvent
    self.__load_mat_file(url)
  File "/tmp/.mount_robot-CrNPEb/usr/src/robot_log_visualizer/ui/gui.py", line 551, in __load_mat_file
    if not self.meshcat_provider.load_model(
  File "/tmp/.mount_robot-CrNPEb/usr/src/robot_log_visualizer/robot_visualizer/meshcat_provider.py", line 72, in load_model
    for folder in get_model_path_from_envs(self.env_list):
  File "/tmp/.mount_robot-CrNPEb/usr/src/robot_log_visualizer/robot_visualizer/meshcat_provider.py", line 50, in get_model_path_from_envs
    return [
  File "/tmp/.mount_robot-CrNPEb/usr/src/robot_log_visualizer/robot_visualizer/meshcat_provider.py", line 53, in <listcomp>
    for f in os.getenv(env).split(os.pathsep)
AttributeError: 'NoneType' object has no attribute 'split'
Aborted (core dumped)
```

**Comment by GiulioRomualdi** [comment]
Fixed in https://github.com/ami-iit/robot-log-visualizer/pull/59/commits/bbfbbc748d57303e488aa1ae05d6eb3bbbb194a2
