### ISSUE TITLE
Crash if the dimension of the data in the "log" is 1x1

### ISSUE THREAD

**Issue by davidegorbani** [ami-iit/robot-log-visualizer#57]
The `robot-log-visualizer` crashes if in the `log` field of the matlab structure generated by the `YarpRobotLogger` there is a data field of dimension 1x1 such as the one shown in the picture.

![Screenshot from 2023-07-14 10-30-58](https://github.com/ami-iit/robot-log-visualizer/assets/101326942/4443a7a1-d665-47d7-b676-f2dd8fc9af78)

The error that I get is the following:

```
Traceback (most recent call last):
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/ui/gui.py", line 627, in open_mat_file
    self.__load_mat_file(file_name)
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/ui/gui.py", line 547, in __load_mat_file
    self.signal_provider.open_mat_file(file_name)
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/file_reader/signal_provider.py", line 140, in open_mat_file
    self.text_logging_data["log"] = self.__populate_text_logging_data(
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/file_reader/signal_provider.py", line 95, in __populate_text_logging_data
    data[key] = self.__populate_text_logging_data(file_object=value)
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/file_reader/signal_provider.py", line 95, in __populate_text_logging_data
    data[key] = self.__populate_text_logging_data(file_object=value)
  File "/home/dgorbani/software/robotology-superbuild/build/install/lib/python3/dist-packages/robot_log_visualizer/file_reader/signal_provider.py", line 75, in __populate_text_logging_data
    if text_ref.shape[0] == len(data[key]["timestamps"]):
TypeError: len() of unsized object
```

I can visualize data of matlab structure in which there is not that data field.

**Comment by GiulioRomualdi** [comment]
Hi @davidegorbani thank you for reporting! 
Unfortunately I don't have time to fix it before the next two weeks. 

If you want you may open a PR with the fix. In theory it should be enough to catch the exception.

Thank you very much!

**Comment by davidegorbani** [comment]
Thank you! I will try to solve it as you suggested.

**Comment by davidegorbani** [comment]
Adding [this line](https://github.com/ami-iit/bipedal-locomotion-framework/blob/ec549f6199885fe276766a17f62b1d178deae4e8/devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml#L20) of code in the `xml` file as suggested by @GiulioRomualdi solved the problem.

**Comment by GiulioRomualdi** [comment]
Hi @davidegorbani by any chance do you have a dataset where I can replicate the issue?

**Comment by davidegorbani** [comment]
Hello @GiulioRomualdi, here is a dataset that I just acquired that replicates the error.

[dataset.zip](https://github.com/ami-iit/robot-log-visualizer/files/12827948/dataset.zip)

**Comment by GiulioRomualdi** [comment]
Fixed by https://github.com/ami-iit/robot-log-visualizer/pull/65

**Comment by davidegorbani** [comment]
Thank you!
