### ISSUE TITLE
Unable to compile the robot-log-visualizer

### ISSUE THREAD

**Issue by fils99** [ami-iit/robot-log-visualizer#85]
I tried to install the visualizer in the superbuild and I got the following error

```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      /tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning:
      ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x
      
      Your build configuration is incomplete and previously worked by accident!
      setuptools_scm requires setuptools>=61
      
      Suggested workaround if applicable:
       - migrating from the deprecated setup_requires mechanism to pep517/518
         and using a pyproject.toml to declare build dependencies
         which are reliably pre-installed before running the build tools
      
        warnings.warn(
      /tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/version.py:102: UserWarning: tag 'RT_prototype_v1.0' no version found
        warnings.warn(f"tag {tag!r} no version found")
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 8, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_integration/setuptools.py", line 55, in _assign_version
          maybe_version = _get_version(config, force_write_version_files=True)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_get_version_impl.py", line 98, in _get_version
          parsed_version = parse_version(config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_get_version_impl.py", line 61, in parse_version
          or parse_scm_version(config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_get_version_impl.py", line 40, in parse_scm_version
          return _entrypoints.version_from_entrypoint(
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_entrypoints.py", line 57, in version_from_entrypoint
          maybe_version: version.ScmVersion | None = fn(root, config=config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/git.py", line 215, in parse
          return _git_parse_inner(
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/git.py", line 259, in _git_parse_inner
          version = version_from_describe(wd, config, describe_command)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/git.py", line 247, in version_from_describe
          return describe_res.parse_success(parse=parse_describe)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/_run_cmd.py", line 81, in parse_success
          return parse(self.stdout)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/git.py", line 245, in parse_describe
          return meta(tag=tag, distance=distance, dirty=dirty, node=node, config=config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/version.py", line 217, in meta
          parsed_version = _parse_tag(tag, preformatted, config)
        File "/tmp/pip-build-env-w6be0dgy/overlay/local/lib/python3.10/dist-packages/setuptools_scm/version.py", line 200, in _parse_tag
          assert version is not None
      AssertionError
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by fils99** [comment]
I tried to recompile again in a clean branch end it worked

**Comment by traversaro** [comment]
Why are you building the repo from source? How are you installing yarp? If you install yarp with robotology-superbuild, I suggest to use robotology-superbuild for robot-log-visualizer.

**Comment by fils99** [comment]
I was updating the robot-log-visualizer, in the end it went fine

**Comment by traversaro** [comment]
> I was updating the robot-log-visualizer, in the end it went fine

Ack, but how was it installed in the first place?

**Comment by fils99** [comment]
With robotology-superbuild

**Comment by traversaro** [comment]
Ahh, so the error comes from the robotology-superbuild, that make sense, sorry for the misunderstanding.
